/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_flag = 1,
  anon_sym_DASHD = 2,
  anon_sym_EQ = 3,
  sym_define_key = 4,
  aux_sym_define_value_token1 = 5,
  anon_sym_DASHp = 6,
  anon_sym_DASH_DASHclass_DASHpath = 7,
  anon_sym_DASH_DASHmain = 8,
  anon_sym_DASHm = 9,
  anon_sym_DASH_DASHconnect = 10,
  anon_sym_COLON = 11,
  sym_connect_host = 12,
  sym_connect_port = 13,
  anon_sym_DASH_DASHdce = 14,
  anon_sym_std = 15,
  anon_sym_full = 16,
  anon_sym_no = 17,
  anon_sym_DASHL = 18,
  anon_sym_DASH_DASHlibrary = 19,
  aux_sym_library_name_token1 = 20,
  anon_sym_DASHhl = 21,
  anon_sym_DASH_DASHhl = 22,
  anon_sym_DASHjs = 23,
  anon_sym_DASH_DASHjs = 24,
  sym_target_path = 25,
  sym_comment = 26,
  sym_include = 27,
  sym_classpath = 28,
  sym_source_file = 29,
  sym_flag_define = 30,
  sym_define_value = 31,
  sym_flag_classpath = 32,
  sym_flag_main = 33,
  sym_flag_connect = 34,
  sym_connect_arg = 35,
  sym_flag_dce = 36,
  sym_flag_library = 37,
  sym__library_value = 38,
  sym_library_name = 39,
  sym_library_version = 40,
  sym_flag_target = 41,
  sym_target_name = 42,
  sym_path = 43,
  aux_sym_source_file_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_flag] = "flag",
  [anon_sym_DASHD] = "-D",
  [anon_sym_EQ] = "=",
  [sym_define_key] = "define_key",
  [aux_sym_define_value_token1] = "define_value_token1",
  [anon_sym_DASHp] = "-p",
  [anon_sym_DASH_DASHclass_DASHpath] = "--class-path",
  [anon_sym_DASH_DASHmain] = "--main",
  [anon_sym_DASHm] = "-m",
  [anon_sym_DASH_DASHconnect] = "--connect",
  [anon_sym_COLON] = ":",
  [sym_connect_host] = "connect_host",
  [sym_connect_port] = "connect_port",
  [anon_sym_DASH_DASHdce] = "--dce",
  [anon_sym_std] = "std",
  [anon_sym_full] = "full",
  [anon_sym_no] = "no",
  [anon_sym_DASHL] = "-L",
  [anon_sym_DASH_DASHlibrary] = "--library",
  [aux_sym_library_name_token1] = "library_name_token1",
  [anon_sym_DASHhl] = "-hl",
  [anon_sym_DASH_DASHhl] = "--hl",
  [anon_sym_DASHjs] = "-js",
  [anon_sym_DASH_DASHjs] = "--js",
  [sym_target_path] = "target_path",
  [sym_comment] = "comment",
  [sym_include] = "include",
  [sym_classpath] = "classpath",
  [sym_source_file] = "source_file",
  [sym_flag_define] = "flag_define",
  [sym_define_value] = "define_value",
  [sym_flag_classpath] = "flag_classpath",
  [sym_flag_main] = "flag_main",
  [sym_flag_connect] = "flag_connect",
  [sym_connect_arg] = "connect_arg",
  [sym_flag_dce] = "flag_dce",
  [sym_flag_library] = "flag_library",
  [sym__library_value] = "_library_value",
  [sym_library_name] = "library_name",
  [sym_library_version] = "library_version",
  [sym_flag_target] = "flag_target",
  [sym_target_name] = "target_name",
  [sym_path] = "path",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_flag] = sym_flag,
  [anon_sym_DASHD] = anon_sym_DASHD,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_define_key] = sym_define_key,
  [aux_sym_define_value_token1] = aux_sym_define_value_token1,
  [anon_sym_DASHp] = anon_sym_DASHp,
  [anon_sym_DASH_DASHclass_DASHpath] = anon_sym_DASH_DASHclass_DASHpath,
  [anon_sym_DASH_DASHmain] = anon_sym_DASH_DASHmain,
  [anon_sym_DASHm] = anon_sym_DASHm,
  [anon_sym_DASH_DASHconnect] = anon_sym_DASH_DASHconnect,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_connect_host] = sym_connect_host,
  [sym_connect_port] = sym_connect_port,
  [anon_sym_DASH_DASHdce] = anon_sym_DASH_DASHdce,
  [anon_sym_std] = anon_sym_std,
  [anon_sym_full] = anon_sym_full,
  [anon_sym_no] = anon_sym_no,
  [anon_sym_DASHL] = anon_sym_DASHL,
  [anon_sym_DASH_DASHlibrary] = anon_sym_DASH_DASHlibrary,
  [aux_sym_library_name_token1] = aux_sym_library_name_token1,
  [anon_sym_DASHhl] = anon_sym_DASHhl,
  [anon_sym_DASH_DASHhl] = anon_sym_DASH_DASHhl,
  [anon_sym_DASHjs] = anon_sym_DASHjs,
  [anon_sym_DASH_DASHjs] = anon_sym_DASH_DASHjs,
  [sym_target_path] = sym_target_path,
  [sym_comment] = sym_comment,
  [sym_include] = sym_include,
  [sym_classpath] = sym_classpath,
  [sym_source_file] = sym_source_file,
  [sym_flag_define] = sym_flag_define,
  [sym_define_value] = sym_define_value,
  [sym_flag_classpath] = sym_flag_classpath,
  [sym_flag_main] = sym_flag_main,
  [sym_flag_connect] = sym_flag_connect,
  [sym_connect_arg] = sym_connect_arg,
  [sym_flag_dce] = sym_flag_dce,
  [sym_flag_library] = sym_flag_library,
  [sym__library_value] = sym__library_value,
  [sym_library_name] = sym_library_name,
  [sym_library_version] = sym_library_version,
  [sym_flag_target] = sym_flag_target,
  [sym_target_name] = sym_target_name,
  [sym_path] = sym_path,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASHD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_define_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_define_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASHp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHclass_DASHpath] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHmain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASHm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHconnect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_connect_host] = {
    .visible = true,
    .named = true,
  },
  [sym_connect_port] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASHdce] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_std] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_full] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASHL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHlibrary] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_library_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASHhl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHhl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASHjs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASHjs] = {
    .visible = true,
    .named = false,
  },
  [sym_target_path] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_classpath] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_define] = {
    .visible = true,
    .named = true,
  },
  [sym_define_value] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_classpath] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_main] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_connect] = {
    .visible = true,
    .named = true,
  },
  [sym_connect_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_dce] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_library] = {
    .visible = true,
    .named = true,
  },
  [sym__library_value] = {
    .visible = false,
    .named = true,
  },
  [sym_library_name] = {
    .visible = true,
    .named = true,
  },
  [sym_library_version] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_target] = {
    .visible = true,
    .named = true,
  },
  [sym_target_name] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(233);
      if (lookahead == '#') ADVANCE(279);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(256);
      if (lookahead == '=') ADVANCE(242);
      if (lookahead == 'f') ADVANCE(225);
      if (lookahead == 'n') ADVANCE(194);
      if (lookahead == 's') ADVANCE(220);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(259);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(269);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(259);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(258);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0) ADVANCE(245);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(244);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(279);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(281);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '-', 141,
        'D', 240,
        'L', 265,
        'h', 239,
        'j', 212,
        'm', 252,
        'p', 246,
        'v', 234,
      );
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(172);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(148);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '-', 32,
        '.', 56,
        'D', 241,
        'L', 266,
        'h', 237,
        'j', 102,
        'm', 253,
        'p', 247,
        'v', 238,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(63);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(164);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(54);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(204);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(94);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(119);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 19:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(118);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead == 'l') ADVANCE(273);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 20:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 21:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 22:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 23:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(97);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(111);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 26:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 27:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 28:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(88);
      if (lookahead == 's') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 29:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(98);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 30:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 31:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'b') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 32:
      ADVANCE_MAP(
        '.', 56,
        'c', 69,
        'd', 34,
        'e', 17,
        'h', 19,
        'j', 103,
        'l', 59,
        'm', 20,
        'n', 45,
        'p', 95,
        't', 58,
        'u', 78,
        'v', 43,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 34:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 35:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(110);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 36:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 37:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'd') ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 38:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'd') ADVANCE(50);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead == 'u') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 39:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'd') ADVANCE(50);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 40:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 41:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(261);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 42:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 43:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 44:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 45:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(116);
      if (lookahead == 'o') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 46:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 47:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(113);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 48:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 49:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 50:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 51:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'f') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 52:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'f') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 53:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'g') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 54:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'g') ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 55:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'h') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 56:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'h') ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 57:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'h') ADVANCE(249);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 58:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 59:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 60:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 61:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(87);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 62:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 63:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(89);
      if (lookahead == 't') ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 64:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 65:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(81);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 66:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 67:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(280);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 68:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 69:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(80);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 70:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 71:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 72:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 73:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 74:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 75:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 76:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 77:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 78:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 79:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(251);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 80:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 81:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 82:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 83:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 84:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 85:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 86:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 87:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 88:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(107);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 89:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(109);
      if (lookahead == 'u') ADVANCE(112);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 90:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 91:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(236);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 92:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 93:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(71);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 94:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 95:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 96:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 97:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(120);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 98:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 99:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 100:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 101:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 102:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(275);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 103:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(277);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 104:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(93);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 105:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 106:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 107:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 108:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 109:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 't') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 110:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 't') ADVANCE(255);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 111:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 't') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 112:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 't') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 113:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 114:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'u') ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 115:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'u') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 116:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'x') ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 117:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'x') ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 118:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'x') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 119:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'y') ADVANCE(238);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 120:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'y') ADVANCE(268);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 121:
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 122:
      if (lookahead == '.') ADVANCE(122);
      if (lookahead == 'h') ADVANCE(123);
      if (lookahead == 'j') ADVANCE(124);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 123:
      if (lookahead == '.') ADVANCE(122);
      if (lookahead == 'l') ADVANCE(278);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 124:
      if (lookahead == '.') ADVANCE(122);
      if (lookahead == 's') ADVANCE(278);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 125:
      if (lookahead == '.') ADVANCE(122);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      if (lookahead == 'a') ADVANCE(142);
      END_STATE();
    case 127:
      if (lookahead == 'a') ADVANCE(229);
      if (lookahead == 'e') ADVANCE(178);
      if (lookahead == 'l') ADVANCE(272);
      END_STATE();
    case 128:
      if (lookahead == 'a') ADVANCE(230);
      END_STATE();
    case 129:
      if (lookahead == 'a') ADVANCE(171);
      END_STATE();
    case 130:
      if (lookahead == 'a') ADVANCE(145);
      END_STATE();
    case 131:
      if (lookahead == 'a') ADVANCE(216);
      END_STATE();
    case 132:
      if (lookahead == 'a') ADVANCE(207);
      END_STATE();
    case 133:
      if (lookahead == 'a') ADVANCE(222);
      END_STATE();
    case 134:
      if (lookahead == 'a') ADVANCE(211);
      END_STATE();
    case 135:
      if (lookahead == 'a') ADVANCE(175);
      END_STATE();
    case 136:
      if (lookahead == 'b') ADVANCE(226);
      END_STATE();
    case 137:
      if (lookahead == 'b') ADVANCE(198);
      if (lookahead == 's') ADVANCE(170);
      END_STATE();
    case 138:
      if (lookahead == 'b') ADVANCE(208);
      END_STATE();
    case 139:
      if (lookahead == 'b') ADVANCE(13);
      END_STATE();
    case 140:
      if (lookahead == 'b') ADVANCE(135);
      END_STATE();
    case 141:
      ADVANCE_MAP(
        'c', 179,
        'd', 143,
        'e', 126,
        'h', 127,
        'j', 213,
        'l', 168,
        'm', 129,
        'n', 155,
        'p', 206,
        't', 167,
        'u', 188,
        'v', 153,
      );
      END_STATE();
    case 142:
      if (lookahead == 'c') ADVANCE(165);
      END_STATE();
    case 143:
      if (lookahead == 'c') ADVANCE(151);
      if (lookahead == 'e') ADVANCE(136);
      if (lookahead == 'i') ADVANCE(214);
      END_STATE();
    case 144:
      if (lookahead == 'c') ADVANCE(221);
      END_STATE();
    case 145:
      if (lookahead == 'c') ADVANCE(158);
      END_STATE();
    case 146:
      if (lookahead == 'd') ADVANCE(262);
      END_STATE();
    case 147:
      if (lookahead == 'd') ADVANCE(152);
      END_STATE();
    case 148:
      if (lookahead == 'd') ADVANCE(160);
      if (lookahead == 'm') ADVANCE(156);
      END_STATE();
    case 149:
      if (lookahead == 'd') ADVANCE(160);
      if (lookahead == 'm') ADVANCE(156);
      if (lookahead == 'u') ADVANCE(218);
      END_STATE();
    case 150:
      if (lookahead == 'e') ADVANCE(234);
      END_STATE();
    case 151:
      if (lookahead == 'e') ADVANCE(260);
      END_STATE();
    case 152:
      if (lookahead == 'e') ADVANCE(161);
      END_STATE();
    case 153:
      if (lookahead == 'e') ADVANCE(205);
      END_STATE();
    case 154:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 155:
      if (lookahead == 'e') ADVANCE(228);
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 156:
      if (lookahead == 'e') ADVANCE(224);
      END_STATE();
    case 157:
      if (lookahead == 'e') ADVANCE(182);
      END_STATE();
    case 158:
      if (lookahead == 'e') ADVANCE(211);
      END_STATE();
    case 159:
      if (lookahead == 'e') ADVANCE(209);
      END_STATE();
    case 160:
      if (lookahead == 'e') ADVANCE(162);
      END_STATE();
    case 161:
      if (lookahead == 'f') ADVANCE(173);
      END_STATE();
    case 162:
      if (lookahead == 'f') ADVANCE(174);
      END_STATE();
    case 163:
      if (lookahead == 'g') ADVANCE(234);
      END_STATE();
    case 164:
      if (lookahead == 'g') ADVANCE(180);
      END_STATE();
    case 165:
      if (lookahead == 'h') ADVANCE(234);
      END_STATE();
    case 166:
      if (lookahead == 'h') ADVANCE(248);
      END_STATE();
    case 167:
      if (lookahead == 'i') ADVANCE(185);
      END_STATE();
    case 168:
      if (lookahead == 'i') ADVANCE(138);
      END_STATE();
    case 169:
      if (lookahead == 'i') ADVANCE(139);
      END_STATE();
    case 170:
      if (lookahead == 'i') ADVANCE(197);
      END_STATE();
    case 171:
      if (lookahead == 'i') ADVANCE(187);
      END_STATE();
    case 172:
      if (lookahead == 'i') ADVANCE(191);
      if (lookahead == 'o') ADVANCE(201);
      if (lookahead == 't') ADVANCE(210);
      END_STATE();
    case 173:
      if (lookahead == 'i') ADVANCE(193);
      END_STATE();
    case 174:
      if (lookahead == 'i') ADVANCE(190);
      END_STATE();
    case 175:
      if (lookahead == 'l') ADVANCE(234);
      END_STATE();
    case 176:
      if (lookahead == 'l') ADVANCE(263);
      END_STATE();
    case 177:
      if (lookahead == 'l') ADVANCE(176);
      END_STATE();
    case 178:
      if (lookahead == 'l') ADVANCE(199);
      END_STATE();
    case 179:
      if (lookahead == 'l') ADVANCE(131);
      if (lookahead == 'o') ADVANCE(189);
      END_STATE();
    case 180:
      if (lookahead == 'l') ADVANCE(196);
      END_STATE();
    case 181:
      if (lookahead == 'l') ADVANCE(128);
      END_STATE();
    case 182:
      if (lookahead == 'l') ADVANCE(169);
      END_STATE();
    case 183:
      if (lookahead == 'l') ADVANCE(173);
      END_STATE();
    case 184:
      if (lookahead == 'm') ADVANCE(200);
      END_STATE();
    case 185:
      if (lookahead == 'm') ADVANCE(158);
      END_STATE();
    case 186:
      if (lookahead == 'n') ADVANCE(234);
      END_STATE();
    case 187:
      if (lookahead == 'n') ADVANCE(250);
      END_STATE();
    case 188:
      if (lookahead == 'n') ADVANCE(147);
      END_STATE();
    case 189:
      if (lookahead == 'n') ADVANCE(192);
      END_STATE();
    case 190:
      if (lookahead == 'n') ADVANCE(158);
      END_STATE();
    case 191:
      if (lookahead == 'n') ADVANCE(183);
      END_STATE();
    case 192:
      if (lookahead == 'n') ADVANCE(154);
      END_STATE();
    case 193:
      if (lookahead == 'n') ADVANCE(150);
      END_STATE();
    case 194:
      if (lookahead == 'o') ADVANCE(264);
      END_STATE();
    case 195:
      if (lookahead == 'o') ADVANCE(184);
      END_STATE();
    case 196:
      if (lookahead == 'o') ADVANCE(140);
      END_STATE();
    case 197:
      if (lookahead == 'o') ADVANCE(186);
      END_STATE();
    case 198:
      if (lookahead == 'o') ADVANCE(217);
      END_STATE();
    case 199:
      if (lookahead == 'p') ADVANCE(235);
      END_STATE();
    case 200:
      if (lookahead == 'p') ADVANCE(219);
      END_STATE();
    case 201:
      if (lookahead == 'p') ADVANCE(219);
      if (lookahead == 'u') ADVANCE(223);
      END_STATE();
    case 202:
      if (lookahead == 'p') ADVANCE(227);
      END_STATE();
    case 203:
      if (lookahead == 'p') ADVANCE(181);
      END_STATE();
    case 204:
      if (lookahead == 'p') ADVANCE(133);
      END_STATE();
    case 205:
      if (lookahead == 'r') ADVANCE(137);
      END_STATE();
    case 206:
      if (lookahead == 'r') ADVANCE(195);
      END_STATE();
    case 207:
      if (lookahead == 'r') ADVANCE(231);
      END_STATE();
    case 208:
      if (lookahead == 'r') ADVANCE(132);
      END_STATE();
    case 209:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 210:
      if (lookahead == 'r') ADVANCE(130);
      END_STATE();
    case 211:
      if (lookahead == 's') ADVANCE(234);
      END_STATE();
    case 212:
      if (lookahead == 's') ADVANCE(274);
      END_STATE();
    case 213:
      if (lookahead == 's') ADVANCE(276);
      END_STATE();
    case 214:
      if (lookahead == 's') ADVANCE(203);
      END_STATE();
    case 215:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 216:
      if (lookahead == 's') ADVANCE(215);
      END_STATE();
    case 217:
      if (lookahead == 's') ADVANCE(150);
      END_STATE();
    case 218:
      if (lookahead == 's') ADVANCE(159);
      END_STATE();
    case 219:
      if (lookahead == 't') ADVANCE(234);
      END_STATE();
    case 220:
      if (lookahead == 't') ADVANCE(146);
      END_STATE();
    case 221:
      if (lookahead == 't') ADVANCE(254);
      END_STATE();
    case 222:
      if (lookahead == 't') ADVANCE(166);
      END_STATE();
    case 223:
      if (lookahead == 't') ADVANCE(202);
      END_STATE();
    case 224:
      if (lookahead == 't') ADVANCE(134);
      END_STATE();
    case 225:
      if (lookahead == 'u') ADVANCE(177);
      END_STATE();
    case 226:
      if (lookahead == 'u') ADVANCE(163);
      END_STATE();
    case 227:
      if (lookahead == 'u') ADVANCE(219);
      END_STATE();
    case 228:
      if (lookahead == 'x') ADVANCE(219);
      END_STATE();
    case 229:
      if (lookahead == 'x') ADVANCE(157);
      END_STATE();
    case 230:
      if (lookahead == 'y') ADVANCE(234);
      END_STATE();
    case 231:
      if (lookahead == 'y') ADVANCE(267);
      END_STATE();
    case 232:
      if (eof) ADVANCE(233);
      if (lookahead == '#') ADVANCE(279);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == ':') ADVANCE(257);
      if (lookahead == '=') ADVANCE(243);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(232);
      if (lookahead != 0) ADVANCE(121);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_flag);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_flag);
      if (lookahead == '-') ADVANCE(149);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_flag);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_flag);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(271);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_flag);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_flag);
      if (lookahead == 'l') ADVANCE(270);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(anon_sym_DASHD);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(anon_sym_DASHD);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_define_key);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '=') ADVANCE(244);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(aux_sym_define_value_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(245);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(anon_sym_DASHp);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(anon_sym_DASHp);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(anon_sym_DASH_DASHclass_DASHpath);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(anon_sym_DASH_DASHclass_DASHpath);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(anon_sym_DASH_DASHmain);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(anon_sym_DASH_DASHmain);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(anon_sym_DASHm);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(anon_sym_DASHm);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(anon_sym_DASH_DASHconnect);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(anon_sym_DASH_DASHconnect);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_connect_host);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(258);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_connect_port);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(259);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(anon_sym_DASH_DASHdce);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(anon_sym_DASH_DASHdce);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(anon_sym_std);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(anon_sym_full);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(anon_sym_no);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(anon_sym_DASHL);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(anon_sym_DASHL);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(anon_sym_DASH_DASHlibrary);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(anon_sym_DASH_DASHlibrary);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(aux_sym_library_name_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(269);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(anon_sym_DASHhl);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(anon_sym_DASHhl);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(anon_sym_DASH_DASHhl);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(anon_sym_DASH_DASHhl);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(anon_sym_DASHjs);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(anon_sym_DASHjs);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(anon_sym_DASH_DASHjs);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(anon_sym_DASH_DASHjs);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(sym_target_path);
      if (lookahead == '.') ADVANCE(122);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 279:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(279);
      END_STATE();
    case 280:
      ACCEPT_TOKEN(sym_include);
      if (lookahead == '.') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(121);
      END_STATE();
    case 281:
      ACCEPT_TOKEN(sym_classpath);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(281);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 232},
  [2] = {.lex_state = 232},
  [3] = {.lex_state = 232},
  [4] = {.lex_state = 232},
  [5] = {.lex_state = 232},
  [6] = {.lex_state = 232},
  [7] = {.lex_state = 232},
  [8] = {.lex_state = 232},
  [9] = {.lex_state = 232},
  [10] = {.lex_state = 232},
  [11] = {.lex_state = 232},
  [12] = {.lex_state = 232},
  [13] = {.lex_state = 232},
  [14] = {.lex_state = 232},
  [15] = {.lex_state = 232},
  [16] = {.lex_state = 232},
  [17] = {.lex_state = 232},
  [18] = {.lex_state = 232},
  [19] = {.lex_state = 232},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_flag] = ACTIONS(1),
    [anon_sym_DASHD] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASHp] = ACTIONS(1),
    [anon_sym_DASH_DASHclass_DASHpath] = ACTIONS(1),
    [anon_sym_DASH_DASHmain] = ACTIONS(1),
    [anon_sym_DASHm] = ACTIONS(1),
    [anon_sym_DASH_DASHconnect] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_connect_port] = ACTIONS(1),
    [anon_sym_DASH_DASHdce] = ACTIONS(1),
    [anon_sym_std] = ACTIONS(1),
    [anon_sym_full] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [anon_sym_DASHL] = ACTIONS(1),
    [anon_sym_DASH_DASHlibrary] = ACTIONS(1),
    [anon_sym_DASHhl] = ACTIONS(1),
    [anon_sym_DASH_DASHhl] = ACTIONS(1),
    [anon_sym_DASHjs] = ACTIONS(1),
    [anon_sym_DASH_DASHjs] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym_flag_define] = STATE(2),
    [sym_flag_classpath] = STATE(2),
    [sym_flag_main] = STATE(2),
    [sym_flag_connect] = STATE(2),
    [sym_flag_dce] = STATE(2),
    [sym_flag_library] = STATE(2),
    [sym_flag_target] = STATE(2),
    [sym_target_name] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_flag] = ACTIONS(7),
    [anon_sym_DASHD] = ACTIONS(9),
    [anon_sym_DASHp] = ACTIONS(11),
    [anon_sym_DASH_DASHclass_DASHpath] = ACTIONS(11),
    [anon_sym_DASH_DASHmain] = ACTIONS(13),
    [anon_sym_DASHm] = ACTIONS(13),
    [anon_sym_DASH_DASHconnect] = ACTIONS(15),
    [anon_sym_DASH_DASHdce] = ACTIONS(17),
    [anon_sym_DASHL] = ACTIONS(19),
    [anon_sym_DASH_DASHlibrary] = ACTIONS(19),
    [anon_sym_DASHhl] = ACTIONS(21),
    [anon_sym_DASH_DASHhl] = ACTIONS(21),
    [anon_sym_DASHjs] = ACTIONS(21),
    [anon_sym_DASH_DASHjs] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_include] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_flag_define] = STATE(3),
    [sym_flag_classpath] = STATE(3),
    [sym_flag_main] = STATE(3),
    [sym_flag_connect] = STATE(3),
    [sym_flag_dce] = STATE(3),
    [sym_flag_library] = STATE(3),
    [sym_flag_target] = STATE(3),
    [sym_target_name] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_flag] = ACTIONS(27),
    [anon_sym_DASHD] = ACTIONS(9),
    [anon_sym_DASHp] = ACTIONS(11),
    [anon_sym_DASH_DASHclass_DASHpath] = ACTIONS(11),
    [anon_sym_DASH_DASHmain] = ACTIONS(13),
    [anon_sym_DASHm] = ACTIONS(13),
    [anon_sym_DASH_DASHconnect] = ACTIONS(15),
    [anon_sym_DASH_DASHdce] = ACTIONS(17),
    [anon_sym_DASHL] = ACTIONS(19),
    [anon_sym_DASH_DASHlibrary] = ACTIONS(19),
    [anon_sym_DASHhl] = ACTIONS(21),
    [anon_sym_DASH_DASHhl] = ACTIONS(21),
    [anon_sym_DASHjs] = ACTIONS(21),
    [anon_sym_DASH_DASHjs] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [sym_include] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_flag_define] = STATE(3),
    [sym_flag_classpath] = STATE(3),
    [sym_flag_main] = STATE(3),
    [sym_flag_connect] = STATE(3),
    [sym_flag_dce] = STATE(3),
    [sym_flag_library] = STATE(3),
    [sym_flag_target] = STATE(3),
    [sym_target_name] = STATE(28),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_flag] = ACTIONS(33),
    [anon_sym_DASHD] = ACTIONS(36),
    [anon_sym_DASHp] = ACTIONS(39),
    [anon_sym_DASH_DASHclass_DASHpath] = ACTIONS(39),
    [anon_sym_DASH_DASHmain] = ACTIONS(42),
    [anon_sym_DASHm] = ACTIONS(42),
    [anon_sym_DASH_DASHconnect] = ACTIONS(45),
    [anon_sym_DASH_DASHdce] = ACTIONS(48),
    [anon_sym_DASHL] = ACTIONS(51),
    [anon_sym_DASH_DASHlibrary] = ACTIONS(51),
    [anon_sym_DASHhl] = ACTIONS(54),
    [anon_sym_DASH_DASHhl] = ACTIONS(54),
    [anon_sym_DASHjs] = ACTIONS(54),
    [anon_sym_DASH_DASHjs] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
    [sym_include] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_EQ,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(62), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [27] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(68), 15,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_COLON,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [52] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_COLON,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(72), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [79] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(78), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(82), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(86), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(90), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(94), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(98), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [223] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(102), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(106), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(110), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(114), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(118), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [343] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(122), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [367] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym_include,
    ACTIONS(126), 14,
      sym_flag,
      anon_sym_DASHD,
      anon_sym_DASHp,
      anon_sym_DASH_DASHclass_DASHpath,
      anon_sym_DASH_DASHmain,
      anon_sym_DASHm,
      anon_sym_DASH_DASHconnect,
      anon_sym_DASH_DASHdce,
      anon_sym_DASHL,
      anon_sym_DASH_DASHlibrary,
      anon_sym_DASHhl,
      anon_sym_DASH_DASHhl,
      anon_sym_DASHjs,
      anon_sym_DASH_DASHjs,
  [391] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      aux_sym_library_name_token1,
    STATE(6), 1,
      sym_library_name,
    STATE(15), 1,
      sym__library_value,
  [404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_std,
      anon_sym_full,
      anon_sym_no,
  [413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_connect_host,
    ACTIONS(134), 1,
      sym_connect_port,
    STATE(12), 1,
      sym_connect_arg,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      aux_sym_define_value_token1,
    STATE(10), 1,
      sym_path,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      aux_sym_library_name_token1,
    STATE(14), 1,
      sym_library_version,
  [446] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      aux_sym_define_value_token1,
    STATE(16), 1,
      sym_define_value,
  [456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym_target_path,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      sym_define_key,
  [470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_target_path,
  [477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
  [484] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_COLON,
  [491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_connect_port,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_classpath,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 27,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 79,
  [SMALL_STATE(8)] = 103,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 151,
  [SMALL_STATE(11)] = 175,
  [SMALL_STATE(12)] = 199,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 247,
  [SMALL_STATE(15)] = 271,
  [SMALL_STATE(16)] = 295,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 343,
  [SMALL_STATE(19)] = 367,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 404,
  [SMALL_STATE(22)] = 413,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 436,
  [SMALL_STATE(25)] = 446,
  [SMALL_STATE(26)] = 456,
  [SMALL_STATE(27)] = 463,
  [SMALL_STATE(28)] = 470,
  [SMALL_STATE(29)] = 477,
  [SMALL_STATE(30)] = 484,
  [SMALL_STATE(31)] = 491,
  [SMALL_STATE(32)] = 498,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_define, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_define, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_library_name, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_library_name, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__library_value, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__library_value, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_value, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_value, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_main, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_main, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_classpath, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_classpath, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_arg, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_connect_arg, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_connect, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_connect, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_dce, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_dce, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__library_value, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__library_value, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_library, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_library, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_define, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_define, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag_target, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag_target, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_arg, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_connect_arg, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_library_version, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_library_version, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_name, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hxml_connect(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hxml_connect",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
