name: Test tree-sitter-hxml parser

on:
  push:
    branches: [main, dev]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test-parser:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Generate parser
        run: npx tree-sitter generate
      - name: Run grammar tests
        run: npx tree-sitter test
      - name: Test example files with comprehensive script
        run: npm run test-examples
  build-bindings:
    runs-on: ubuntu-latest
    needs: test-parser
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Generate parser
        run: npx tree-sitter generate
      - name: Build C library
        run: make
      - name: Test C compilation
        run: |
          if [ -f "libtree-sitter-hxml.a" ]; then
            echo "✅ Static library built successfully"
          else
            echo "❌ Static library build failed"
            exit 1
          fi

          if [ -f "libtree-sitter-hxml.so" ]; then
            echo "✅ Shared library built successfully"
          else
            echo "❌ Shared library build failed"  
            exit 1
          fi
      - name: Upload parser artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parser-binaries
          path: |
            libtree-sitter-hxml.a
            libtree-sitter-hxml.so
            src/parser.c
