name: Test tree-sitter-hxml parser

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-parser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate parser
        run: npx tree-sitter generate

      - name: Run grammar tests
        run: npx tree-sitter test

      - name: Test example files with comprehensive script
        run: ./scripts/test-examples.sh

      - name: Validate specific edge cases
        run: |
          echo "🔍 Validating specific edge cases..."

          # Test complex library versions
          echo "--library test:1.2.3-beta.4" | npx tree-sitter parse

          # Test complex defines
          echo "-D complex=value:with:colons" | npx tree-sitter parse

          # Test resource with names
          echo "--resource file.png@name" | npx tree-sitter parse

          # Test various network addresses
          echo "--connect [::1]:8080" | npx tree-sitter parse
          echo "--connect localhost:6000" | npx tree-sitter parse
          echo "--connect 127.0.0.1:9000" | npx tree-sitter parse

          echo "✅ All edge case validations passed!"

  build-bindings:
    runs-on: ubuntu-latest
    needs: test-parser

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate parser
        run: npx tree-sitter generate

      - name: Build C library
        run: make

      - name: Test C compilation
        run: |
          if [ -f "libtree-sitter-hxml.a" ]; then
            echo "✅ Static library built successfully"
          else
            echo "❌ Static library build failed"
            exit 1
          fi

          if [ -f "libtree-sitter-hxml.so" ]; then
            echo "✅ Shared library built successfully"
          else
            echo "❌ Shared library build failed"  
            exit 1
          fi

      - name: Upload parser artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parser-binaries
          path: |
            libtree-sitter-hxml.a
            libtree-sitter-hxml.so
            src/parser.c
